// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czpspelyldfrvuqctnpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cHNwZWx5bGRmcnZ1cWN0bnBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDUxNDEsImV4cCI6MjA2NjMyMTE0MX0.tNVwR5GAa-Bxv1yJCZV5VqN_uaI0IS9Ef7MEqwByq6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);